#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: must be root\e[00m"
	exit 1
fi
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
case "$1" in
	kde)
		startx startkde -- :$2
		;;	

	gnome)
		startx gnome-shell -- :$2
		;;

	unity)
		startx unity -- :$2
		;;

	xfce)
		startx xfce4-session -- :$2
		;;

	virtualbox)
		startx virtualbox -- :$2
		;;

	install)
		apt-get -q update
		apt-get -y install xubuntu-desktop gnome kubuntu-desktop virtualbox
		echo -e "\e[00;1;92mFinished...\e[00m"
		;;

	*)
		echo "usage: $(basename $0) {kde|gnome|unity|xfce|virtualbox|install} 1-6"
		;;
esac
rm -f /run/$(basename $0).pid
exit 0
